### ISSUE TITLE
Maybe free()?

### ISSUE THREAD

**Issue by MartinSkachkov** [stoychoX/Data-structures-and-algorithms#2]
https://github.com/stoychoX/Data-structures-and-algorithms/blob/8b97246a36150dd7ea408ae16b7e9a696d5be91d/Seminar05/LinkedList.hpp#L201

Здрасти, Стойчо. Точно над този ред, в който викаме move(), във функцията move op()= не трябва да ли извикаме free(), за да изчистим паметта на *this обекта и след това вече да крадем указателите на other или аз нещо не разбирам какво става xD?

**Comment by stoychoX** [comment]
Да, на семинара го оправихме, но забравих да го пушна. Мерси!
